# -*- coding: utf-8 -*-
"""exercicio_ebac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZcjI8gbs3MkZxq_j71em32l6ySofNAH
"""

import requests
import time
import csv
from bs4 import BeautifulSoup

# global headers to be used for requests
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9'
}


def extract_movie_details(movie):
    title_element = movie.find('td', class_='titleColumn').find('a')
    title = title_element.text.strip() if title_element else ''

    date_element = movie.find('td', class_='titleColumn').find('span', class_='secondaryInfo')
    date = date_element.text.strip() if date_element else ''

    rating_element = movie.find('td', class_='ratingColumn imdbRating').find('strong')
    rating = rating_element.text.strip() if rating_element else ''

    with open('movies.csv', mode='a', newline='', encoding='utf-8') as file:
        movie_writer = csv.writer(file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        movie_writer.writerow([title, date, rating])


def extract_movies():
    popular_movies_url = 'https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm'
    response = requests.get(popular_movies_url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')

    movies = soup.select('tbody.lister-list tr')
    for movie in movies:
        extract_movie_details(movie)


def main():
    start_time = time.time()

    # IMDB Most Popular Movies - Extracting movie details
    with open('movies.csv', mode='w', newline='', encoding='utf-8') as file:
        movie_writer = csv.writer(file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        movie_writer.writerow(['Title', 'Date', 'Rating'])

    extract_movies()

    end_time = time.time()
    print('Total time taken:', end_time - start_time)


if __name__ == '__main__':
    main()